#!/bin/sh

# ----------------------------------------------------------------------
# SANE CONFIGURATION
# ----------------------------------------------------------------------

# setup some basic variables
: ${HOME:=~}
: ${LOGNAME:=$(id -un)}
: ${CDPATH:=.:$HOME/PhD:$HOME/code:$HOME/projects}
export HOME LOGNAME CDPATH

# enable en_US locale w/ utf-8 encodings if not already configured
: ${LANG:="en_US.UTF-8"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

# readline inputrc
: ${INPUTRC:=~/.inputrc}
export INPUTRC

# path
PATH="/usr/local/bin:$PATH:/usr/local/sbin:/usr/sbin:/sbin"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
export PATH

# ls colors
LSCOLORS="ExDxCxDxBxEGEDABAGACAD"
export LSCOLORS

# bring in local system profile
[ -r ~/.profile ] && . ~/.profile
