#!/bin/sh

# ----------------------------------------------------------------------
# SANE CONFIGURATION
# ----------------------------------------------------------------------

umask 0022            # default umask
ulimit -S -c 0        # disable core dumps

# enable en_US locale w/ utf-8 encodings if not already configured
: ${LANG:="en_US.UTF-8"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

# path
PATH="/usr/local/bin:$PATH:/usr/local/sbin:/usr/sbin:/sbin"
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
export PATH
