#!/bin/sh

# ----------------------------------------------------------------------
# SANE CONFIGURATION
# ----------------------------------------------------------------------

stty -ixon -ixoff     # disable flow control
unset MAILCHECK       # forget about mail check

# ----------------------------------------------------------------------
# ENVIRONMENT CONFIGURATION
# ----------------------------------------------------------------------

# setup some basic variables
: ${HOME:=~}
: ${LOGNAME:=$(id -un)}
: ${CDPATH:=.:$HOME/PhD:$HOME/Code:$HOME/Projects}
export HOME LOGNAME CDPATH

: ${INPUTRC:=~/.inputrc}
export INPUTRC

# ls colors
LSCOLORS="ExDxCxDxBxEGEDABAGACAD"
export LSCOLORS

# See what we have to work with ...
[ -n "$(command -v vim)" ] && EDITOR=vim || EDITOR=vi
export EDITOR

# hg
[ -n "$(command -v hg)" ] && export HGEDITOR=$EDITOR

# git
[ -n "$(command -v git)" ] && export GIT_EDITOR=$EDITOR

# pager
[ -n "$(command -v less)" ] && PAGER="less -FiRSX" || PAGER=more
MANPAGER="$PAGER"
export PAGER MANPAGER

# browser
[ -n "$DISPLAY" ] && BROWSER=chrome || BROWSER=links
export BROWSER

# ignore backups, CVS directories, python bytecode, vim swap files
export FIGNORE="~:CVS:#:.pyc:.swp:.swa:apache-solr-*"

# Less Colors for Man Pages
export LESS_TERMCAP_md=$'\E[01;38;5;166m'          # begin bold
export LESS_TERMCAP_mb=$'\E[01;38;5;136m'          # begin blinking
export LESS_TERMCAP_us=$'\E[04;38;5;136m'          # begin underline
export LESS_TERMCAP_so=$'\E[01;38;5;233;48;5;166m' # begin standout-mode - info box
export LESS_TERMCAP_se=$'\E[0m'                    # end standout-mode
export LESS_TERMCAP_ue=$'\E[0m'                    # end underline
export LESS_TERMCAP_me=$'\E[0m'                    # end mode

# ----------------------------------------------------------------------
# SHELL ALIASES
# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'

# hg
[ -n "$(command -v hg)" ] && alias h='hg'

# git
[ -n "$(command -v git)" ] && alias g='git'

# disk usage with human sizes and minimal depth
[ "$(uname)" = "Darwin" ] && DU_DEPTH="-d 1" || DU_DEPTH="--max-depth=1"
alias du1="command du -h $DU_DEPTH"

# find extension
fx() { find . -name '*.'$* }

# find with name
fn() { find . -name "*$**" }

# # find files with word
fw() {find . -name "*.$1" -exec grep -i -H "$2" {} \; }

# ----------------------------------------------------------------------
# LS CONFIGURATION
# ----------------------------------------------------------------------

# we always pass these to ls(1)
[ "$(uname)" = "Darwin" ] && LS_COMMON="-hBG" || LS_COMMON="-hB --color=auto"

# setup the main ls alias if we've established common args
alias ls="command ls $LS_COMMON"

# these use the ls aliases above
alias l="ls -la"
alias ll="ls -l"
alias l.="ls -d .*"
