gui:
  theme:
    activeBorderColor:
      - "#7aa2f7"
      - bold
    inactiveBorderColor:
      - "#5b6ea8"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2a2f45"
    cherryPickedCommitBgColor:
      - "#323856"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    unstagedChangesColor:
      - "#f7768e"
    defaultFgColor:
      - "#c0caf5"
    searchingActiveBorderColor:
      - "#e0af68"

  authorColors:
    "*": "#bb9af7"
